account/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from account.views import SignupView, LoginView, LogoutView, DeleteView
from account.views import ConfirmEmailView
from account.views import ChangePasswordView, PasswordResetView, PasswordResetTokenView
from account.views import SettingsView


urlpatterns = patterns("",
    url(r"^signup/$", SignupView.as_view(), name="account_signup"),
    url(r"^login/$", LoginView.as_view(), name="account_login"),
    url(r"^logout/$", LogoutView.as_view(), name="account_logout"),
    url(r"^confirm_email/(?P<key>\w+)/$", ConfirmEmailView.as_view(), name="account_confirm_email"),
    url(r"^password/$", ChangePasswordView.as_view(), name="account_password"),
    url(r"^password/reset/$", PasswordResetView.as_view(), name="account_password_reset"),
    url(r"^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$", PasswordResetTokenView.as_view(), name="account_password_reset_token"),
    url(r"^settings/$", SettingsView.as_view(), name="account_settings"),
    url(r"^delete/$", DeleteView.as_view(), name="account_delete"),
)

coupons/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

# Uncomment the next two lines to enable the admin:

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'coupons.views.home', name='home'),
    # url(r'^coupons/', include('coupons.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

########################################################################################
# Web
########################################################################################
urlpatterns += patterns('web.views.main',
    url(r'^$', 'index'),
    url(r'^privacy-and-terms/$', 'privacy'),
    url(r'^coupons/(?P<company_name>[a-z0-9-_]+)/$', 'coupons_for_company'),
    url(r'^coupons/(?P<company_name>[a-z0-9-_]+)/(?P<company_id>[\d]+)/$', 'coupons_for_company'),

    url(r'^coupons/(?P<company_name>[a-z0-9-_]+)/page/(?P<current_page>[\d]+)/$', 'coupons_for_company'),
    url(r'^coupons/(?P<company_name>[a-z0-9-_]+)/(?P<company_id>[\d]+)/page/(?P<current_page>[\d]+)/$', 'coupons_for_company'),

    url(r'^coupons/(?P<company_name>[a-z0-9-_]+)/page/(?P<current_page>[\d]+)/categories/(?P<category_ids>sh_[a-fA-F0-9]+)/$', 'coupons_for_company'),
    url(r'^coupons/(?P<company_name>[a-z0-9-_]+)/(?P<company_id>[\d]+)/page/(?P<current_page>[\d]+)/categories/(?P<category_ids>sh_[a-fA-F0-9]+)/$', 'coupons_for_company'),

    url(r'^coupons/(?P<company_name>[a-z0-9-_]+)/(?P<coupon_label>[a-z0-9-]+)/(?P<coupon_id>[\d]+)/$', 'open_coupon'),
    #do not kill old links:
    url(r'^coupon/(?P<company_name>[a-z0-9-_]+)/(?P<coupon_label>[a-z0-9-]+)/(?P<coupon_id>[\d]+)/$', 'redirect_to_open_coupon'),


    url(r'^categories/(?P<category_code>[A-z0-9-]+)/page/(?P<current_page>[\d]+)/$', 'category'),
    url(r'^categories/(?P<category_code>[A-z0-9-]+)/$', 'category'),
    url(r'^categories/$', 'categories'),
    url(r'^stores/(?P<page>[A-Za-z]+)/$', 'stores'),
    url(r'^stores/$', 'stores'),

    url(r'^blog/', include('articles.urls')),
    url(r'^robots\.txt$', 'robots_txt'),
    url(r'^sitemap\.xml$', 'sitemap'),
)

urlpatterns += patterns('web.views.ajax',
    url(r'^a/subscribe/$', 'ajax_subscribe'),
)

urlpatterns += patterns('tracking.views',
    url(r'^a/clk/$', 'click_track'),
)

urlpatterns += patterns('web.views.search',
    url(r'^search/$', 'search')
)

urlpatterns += patterns('web.views.email',
    url(r'^emailA$', 'email_a'),
    url(r'^emailB$', 'email_b'),
    url(r'^emailC$', 'email_c'),
    url(r'^emailD$', 'email_d'),
)

handler404 = 'web.views.main.index'

########################################################################################
# WebSvcs
########################################################################################

urlpatterns += patterns('websvcs.views.image',
    url(r'^s/image/(?P<image_url>.+)/(?P<height>[\d]+)x(?P<width>[\d]+)/$', 'image_resize'),
    url(r'^s/image/(?P<image_url>http.+)/$', 'image')
)

urlpatterns += patterns('websvcs.views.subscriptions',
    url(r'^e/subscribe/$', 'email_subscribe')
)

core/models.py
from __future__ import unicode_literals
import os
import urllib
import datetime
import urlparse

from django.conf import settings
from django.db import models
from django.db.models.query_utils import Q
from django.template.defaultfilters import slugify
from django.core.paginator import Paginator
from core.util import print_stack_trace, get_first_google_image_result, get_description_tag_from_url
from tracking.commission.skimlinks import get_merchant_description


def get_descriptive_image(name):
    return get_first_google_image_result(name)

def get_directed_image(image_url):
    try:
        return "/s/image/%s" % urllib.quote_plus(image_url)
    except:
        return settings.DEFAULT_IMAGE

def get_description(model):
    if not model.directlink:
        if model.name:
            return model.name
        else:
            return ""
    return get_description_tag_from_url(model.directlink)

base_description = "PennyWyse | Hand Verified Coupon Codes"
icon_url = "http://pennywyse.com/static/img/fbog.png"

#######################################################################################################################
#
# Category
#
#######################################################################################################################

class Category(models.Model):
    ref_id          = models.CharField(max_length=255, db_index=True, blank=True, null=True)
    code            = models.CharField(max_length=255,blank=True, null=True, db_index=True)
    name            = models.CharField(max_length=255,blank=True, null=True, db_index=True)
    description     = models.CharField(max_length=255,blank=True, null=True)
    parent          = models.ForeignKey("Category", blank=True, null=True)
    image           = models.TextField(blank=True, null=True)

    date_added      = models.DateTimeField(default=datetime.datetime.now(), auto_now_add=True)
    last_modified   = models.DateTimeField(default=datetime.datetime.now(), auto_now=True, auto_now_add=True)

    def save(self, *args, **kwargs):
      if not self.image:
          self.image = get_descriptive_image(self.code)
      super(Category, self).save(*args, **kwargs)

    def get_coupons(self):
      return self.coupon_set.all().order_by("-created")

    def get_active_coupons(self):
        return self.coupon_set.all().filter(Q(end__gt=datetime.datetime.now()) | Q(end__isnull=True)).order_by("-created")

    def get_coupon_count(self):
      return self.get_active_coupons().count()

    def get_coupon_categories(self):
      return Category.objects.filter(
        coupon__id__in=self.get_active_coupons().values_list('id')).distinct().order_by('name')

    def coupons_in_categories(self, selected_categories):
      return Paginator(self.get_active_coupons().filter(
        Q(categories__id__in=selected_categories) | Q(categories__id__isnull=True)), 10)

    def display_name(self):
      return self.name

    def local_path(self):
      return "/categories/{0}/".format(self.code)

    def page_description(self):
      return "Coupons for {0} | {1}".format(self.name, base_description)

    def page_title(self):
      return "Coupons for {0} | {1}".format(self.name, base_description)

    def og_title(self):
      return "Coupons for {0}".format(self.name)

    def og_description(self):
      return "Hand Verified Coupon Codes for {0} from PennyWyse.".format(self.name)

    def og_image(self):
      return icon_url

    def og_url(self):
      return "{0}{1}".format(settings.BASE_URL_NO_APPENDED_SLASH, self.local_path())

    def __unicode__(self):  # Python 3: def __str__(self):
      return "%s %s" % (self.code, self.name)

#######################################################################################################################
#
# DealType
#
#######################################################################################################################

class DealType(models.Model):
    code            = models.CharField(max_length=255,blank=True, null=True, db_index=True)
    name            = models.CharField(max_length=255,blank=True, null=True, db_index=True)
    description     = models.CharField(max_length=255,blank=True, null=True)

    date_added      = models.DateTimeField(default=datetime.datetime.now(), auto_now_add=True)
    last_modified   = models.DateTimeField(default=datetime.datetime.now(), auto_now=True, auto_now_add=True)

    def __unicode__(self):  # Python 3: def __str__(self):
        return "%s %s" % (self.code, self.name)

#######################################################################################################################
#
# Merchant
#
#######################################################################################################################

class MerchantManager(models.Manager):

    def get_popular_companies(self, how_many=8):
        return Merchant.objects.exclude(coupon__isnull=True)[:how_many]

class Merchant(models.Model):
    ref_id          = models.CharField(max_length=255, db_index=True, blank=True, null=True)
    name            = models.CharField(max_length=255, db_index=True, blank=True, null=True)
    name_slug       = models.CharField(max_length=255, db_index=True, blank=True, null=True)
    image           = models.TextField(blank=True, null=True)

    description     = models.TextField(blank=True, null=True) #loaded from the target link
    coupon_count    = models.IntegerField(default=0)

    link            = models.TextField(blank=True, null=True)
    directlink      = models.TextField(blank=True, null=True)
    skimlinks       = models.TextField(blank=True, null=True)
    redirect        = models.NullBooleanField()

    date_added      = models.DateTimeField(default=datetime.datetime.now(), auto_now_add=True)
    last_modified   = models.DateTimeField(default=datetime.datetime.now(), auto_now=True, auto_now_add=True)

    objects = MerchantManager()

    def get_top_coupon(self):
        try:
            top_coupon = self.get_active_coupons().filter(short_desc__icontains="%").order_by("-created")
            if top_coupon:
                return top_coupon[0]
            else:
                top_coupon = self.get_active_coupons().filter(short_desc__icontains="$").order_by("-created")
                if top_coupon:
                    return top_coupon[0]
                else:
                    return list(self.get_active_coupons()[:1])[0]
        except:
            return ""

    def get_coupons(self):
        return self.coupon_set.all().order_by("-created")

    def get_active_coupons(self):
        return self.coupon_set.all().filter(Q(end__gt=datetime.datetime.now()) | Q(end__isnull=True)).order_by("-created")

    def get_coupon_categories(self):
        categories = set()
        for c in self.get_active_coupons():
            for cat in c.categories.all():
                categories.add(cat)
        categories = sorted(list(categories), key=lambda cat: cat.name)
        return categories

    def get_coupon_count(self):
        return self.get_active_coupons().count()

    def get_image(self):
        return get_directed_image(self.image)

    def refresh_coupon_count(self):
        self.coupon_count = self.get_coupon_count()
        self.save()

    def save(self, *args, **kwargs):
        if not self.image:
            if self.ref_id:
                try:
                    logo_path = "static/img/logos/%s.gif" % self.ref_id
                    with open(os.path.join(settings.BASE_DIR,logo_path)): pass
                    # logo exists
                    self.image = settings.BASE_URL_NO_APPENDED_SLASH + "/" + logo_path
                except:
                    try:
                        logo_path = "static/img/logos/%s.jpg" % self.ref_id
                        with open(os.path.join(settings.BASE_DIR,logo_path)): pass
                        # logo exists
                        self.image = settings.BASE_URL_NO_APPENDED_SLASH + "/" + logo_path
                    except:
                        self.image = get_descriptive_image(self.name + " logo")
        if not self.description:
            self.description = get_description(self)
        self.name_slug = slugify(self.name)
        super(Merchant, self).save(*args, **kwargs)

    def __unicode__(self):  # Python 3: def __str__(self):
        return "%s %s" % (self.ref_id, self.name)

    def skimlinks_description(self):
        skim_desc = get_merchant_description(self.name_slug)
        if skim_desc == None:
          skim_desc = self.description
        return skim_desc

    def featured_coupon(self):
        active = self.get_active_coupons().filter(Q(end__gt = datetime.datetime.now()) | Q(end = None))
        active_codes = active.exclude(code = None)
        featured = None

        #active w/code and in apparel
        for coupon in active_codes:
            if coupon.in_category('apparel'):
                featured = coupon

        #active w/code NOT in apparel
        if featured == None and active_codes.exists():
            featured = active_codes[0]

        #active in apparel W/O code
        if featured == None and active.exists():
            for coupon in active:
                if coupon.in_category('apparel'):
                    featured = coupon
            if featured == None:
                featured = codes[0]

        return featured

    def display_name(self):
      return self.name

    def local_path(self):
      return "/coupons/{0}/{1}/".format(self.name_slug, self.id)

    def page_description(self):
      return "Coupons for {0} | {1} | {2}".format(self.name, self.description, base_description)

    def page_title(self):
      return "Coupons for {0} | {1}".format(self.name, base_description)

    def og_title(self):
      return "Coupons for {0}".format(self.name)

    def og_description(self):
      return "{0} | Hand Verified Coupon Codes for {1} from PennyWyse.".format(self.description, self.name)

    def og_image(self):

web/views/email.py
import datetime
from django.conf import settings
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from core.models import Coupon, Merchant
from tracking.commission.skimlinks import merchant_slugs

def date_string():
    date_string = datetime.datetime.now().strftime("%d, %b %Y")

def coupon_tuple(link_type):
    coupon_data = []
    index = 0
    for slug in merchant_slugs(None):
        index += 1
        merchant = Merchant.objects.filter(name_slug=slug)[0]
        coupon = merchant.featured_coupon()
        merchant_link = "http://pennywyse.com/coupons/{0}/{1}".format(merchant.name_slug, merchant.id)
        if link_type == 'merchant':
          link_address = merchant_link
        else:
          link_address = "{0}{1}".format(settings.BASE_URL_NO_APPENDED_SLASH, coupon.local_path())
        params = "utm_medium=mailchimp&utm_source=newsletter&utm_campaign=promo&utm_term={0}".format(merchant.name_slug)
        link_address = "{0}?{1}".format(link_address, params)
        merchant_link = "{0}?{1}".format(merchant_link, params)
        coupon_data.append([coupon, index, link_address, merchant_link])
    return coupon_data

def store_description(request):
    desc = request.GET.get('store_description', True)
    if (desc == 'False') | (desc == 'false'):
        return False
    else:
        return True


def email_a(request):
    context = {
        'coupon_data': coupon_tuple('coupon'),
        'date_string': date_string(),
        'show_image': True,
        'store_description': store_description(request)
    }
    return render_to_response("email.html", context)

def email_b(request):
    context = {
        'coupon_data': coupon_tuple('merchant'),
        'date_string': date_string(),
        'show_image': True,
        'store_description': store_description(request)
    }
    return render_to_response("email.html", context)

def email_c(request):
    context = {
        'coupon_data': coupon_tuple('coupon'),
        'date_string': date_string(),
        'show_image': False,
        'store_description': store_description(request)
    }
    return render_to_response("email.html", context)

def email_d(request):
    context = {
        'coupon_data': coupon_tuple('merchant'),
        'date_string': date_string(),
        'show_image': False,
        'store_description': store_description(request)
    }
    return render_to_response("email.html", context)

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{{ page_title }}</title>
    <meta name="description" content="{{ page_description }}">
    <meta name="viewport" content="width=device-width">

    {# Place favicon.ico and apple-touch-icon.png in the root directory #}
    <link rel="shortcut icon" type="image/x-icon" href="/static/img/favicon.ico">
    <link rel="apple-touch-icon" href="/static/img/favicon.png" />

    <link rel="stylesheet" href="/static/css/normalize.css">
    <link rel="stylesheet" href="/static/css/foundation.css">
    <!--<link href='http://fonts.googleapis.com/css?family=Ubuntu:400,300,700' rel='stylesheet' type='text/css'>-->
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700,700italic,900,400italic,300' rel='stylesheet' type='text/css'>

    {# <!--<link rel="stylesheet" href="/static/css/ubuntu.css">--> #}
    <link rel="stylesheet" href="/static/css/flexslider.css">
    <link rel="stylesheet" href="/static/css/main.css?d=1">
    <link rel="stylesheet" href="/static/css/mq-0.css" media="screen and (max-width: 32.5em)" />
    <link rel="stylesheet" href="/static/css/mq-32.css" media="screen and (min-width: 32.5em)" />
    <link rel="stylesheet" href="/static/css/mq-48.css" media="screen and (min-width: 48em)" />
    <link rel="stylesheet" href="/static/css/mq-67.css" media="screen and (min-width: 67.5em)" />
    <link rel="stylesheet" href="/static/css/carousel.css"/>
    <link rel="stylesheet" href="/static/css/header.css">
    <link rel="canonical" href="{{ canonical_url }}">

    <!--[if (lt IE 9)&(!IEMobile)]>
    <link rel="stylesheet" href="/static/css/foundation-ie8.css">
    <link rel="stylesheet" href="/static/css/mq-32.css"/>
    <link rel="stylesheet" href="/static/css/mq-48.css"/>
    <link rel="stylesheet" href="/static/css/mq-67.css"/>
    <![endif]-->

    <script src="/static/js/vendor/modernizr-2.6.2.min.js"></script>
    {# <!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> --> #}
    <script>window.jQuery || document.write('<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"><\/script>')</script>
    <script src="/static/js/plugins.js"></script>

	{% block head_tags %}
    {% endblock %}

    {% block fbtags %}
        <meta property="og:image" content="{{ og_image }}"/>
        <meta property="og:title" content="{{ og_title }}"/>
        <meta property="og:description" content="{{ og_description }}"/>
        <meta property="og:url" content="{{ og_url }}"/>
    {% endblock %}

</head>
<body>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<div class="page home">
    <header role="banner" class="cf">
      {% include 'layouts/_header.html' %}
      {% block header_block %}
      {% endblock %}
      {% block newsletter_subscription %}
      		{% include 'layouts/_newsletter_subscription_bar.html' %}
      {% endblock %}
    </header>

    {% block main %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    <footer role="contentinfo">
        {% block popular_companies %}
	        <div class="stripe-regular">
	            <div class="row">
	                <div class="column">
	                    <h2>Popular Companies</h2>
	                </div>
	            </div>
	            <div class="row collapse">
	                <div class="column">
	                    <div class="popular-companies flexslider">
	                        <ul class="rr slides pop-companies">
	                            {% for pop_company in pop_companies %}
	                            <li>
	                                <a href="{% url 'web.views.main.coupons_for_company' pop_company.name_slug pop_company.id %}" class="wrapper-5 small">
	                                  <img src="{{ pop_company.get_image }}" alt="{{ pop_company.name }}">
	                                </a>
	                            </li>
	                            {% endfor %}
	                        </ul>
	                    </div>
	                </div>
	            </div>
	        </div>
        {% endblock %}

        <div class="stripe-dark pre-footer-wrap">
            <div class="row">
                <div class="large-5 columns">
                    <h3 class="alt">About</h3>
                    <p>
                        {{ WEBSITE_NAME }} is America's best and largest source for working coupon codes. All codes on PennyWyse are hand verified by a team right here in the US. We have all the best coupons and deals from over 6,000 brands and retailers. So if its a great coupon, we will have it and we will give you the simplest way to find it and use it.
                    </p>
                </div>
                <div class="small-6 large-3 large-offset-1 columns">

                </div>
                <nav class="small-6 large-2 large-offset-1 columns">
                    <h3 class="alt">Menu</h3>
                    <ul class="rr footer-menu">
                        <li><a href="/">Home</a></li>
                        <li><a href="/privacy-and-terms/" target="_blank">Terms &amp; Conditions</a></li>
                        <li><a href="/privacy-and-terms/" target="_blank">Privacy Policy</a></li>
                    </ul>
                </nav>
            </div>
        </div>

        <div class="stripe-darker footer-wrap">
            <div class="row">
                <div class="large-3 columns">
                    <div class="logo">
                        <a href="#">{{ WEBSITE_NAME }}</a><span style="font-style:normal;font-size:30px;">™</span>
                    </div>
                </div>
                <div class="large-6 columns">
                    <div class="copyright">Copyright &copy; 2013, {{ WEBSITE_NAME }}. All rights reserved.</div>
                </div>
                <div class="large-3 columns">
                    <ul class="rr social">
                        <li><a href="http://www.twitter.com/getpennywyse" target="_blank" class="ir tw">Twitter</a></li>
                        <li><a href="http://www.facebook.com/getpennywyse" target="_blank" class="ir fb">Facebook</a></li>
                    </ul>
                </div>
            </div>
        </div>

    </footer>

</div>

    <script src="/static/js/main.js"></script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

//        ga('create', 'UA-42711247-1', 'pennywyse.com');
        ga('create', 'UA-42711247-1', 'pennywyse.com');
        ga('send', 'pageview');
    </script>
    <script type="text/javascript">
        var clicky_site_ids = clicky_site_ids || [];
        clicky_site_ids.push(100637453);
        (function() {
            var s = document.createElement('script');
            s.type = 'text/javascript';
            s.async = true;
            s.src = '//static.getclicky.com/js';
            ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
        })();
    </script>
    <script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
        typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);
    b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
    mixpanel.init("3d3d512c8e3abb7052561dcaa0187132");</script>
    {% block end_of_body %}
    {% endblock %}
</body>
</html>

templates/categories.html
{% extends "base.html" %}
{% load humanize %}

{% block fbtags %}
    <meta property="og:image" content="{{ BASE_URL_NO_APPENDED_SLASH }}{{ merchant.get_image }}"/>
    <meta property="og:title" content="Hand Verified Coupon Codes for {{ merchant.name }} from PennyWyse"/>
    <meta property="og:url" content="{{ CURRENT_URL }}"/>
{% endblock %}

{% block header_block %}
  <h1 class="text-center">Categories</h1>
{% endblock %} {# header #}

{% block main %}
<div class="stripe-regular" style="border-bottom: 2px solid #DDDDDD">
  <div role="main">
    <section class="row category-index">
      <ul class='categories-list rr'>
        {% for category in categories %}
          <li class='category'>
            <a class='round3' href='/categories/{{ category.code }}'>
              {{ category.name }}
            {% if category.category_set.all.exists %}
                <span class='arrow-down'/>
              </a>
              <div class='subcategories'>
                {% for subcat in category.category_set.all %}
                <div class='subcategory'><div class='centering'>
                  <a href='/categories/{{ subcat.code }}'>{{ subcat.name }}</a>
                </div></div>
                {% endfor %}
              </div>
            {% else %}
              </a>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    </section>
  </div>
</div>
{% endblock %} {# main #}

{% block end_of_body %}
<script type="text/javascript">
    try{
        mixpanel.track("Categories Index Page Opened",{
            "utm_source"    : "{{ visitor.acquisition_source }}",
            "utm_medium"    : "{{ visitor.acquisition_medium }}",
            "utm_term"      : "{{ visitor.acquisition_term }}",
            "utm_content"   : "{{ visitor.acquisition_content }}",
            "utm_campaign"  : "{{ visitor.acquisition_campaign }}"
        });
    }catch(e){}
</script>
{% endblock %}